//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceID { get; set; }
        public int OrderID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> Units { get; set; }
    }
}
